import { GoogleGenAI, Type } from "@google/genai";
import { Lead, SearchParams, MyCompany } from "../types";

// Primary recommended model per Gemini API guidelines, with fallbacks for high demand spikes
const PRIMARY_MODEL = "gemini-3.8-flash";
const FALLBACK_MODELS = [
  "gemini-3.6-flash",
  "gemini-3.1-flash-lite",
  "gemini-flash-latest",
  "gemini-3.5-flash-lite",
];

function getResolvedApiKey(): string {
  try {
    const metaEnv = typeof import.meta !== 'undefined' ? (import.meta as any).env : null;
    if (metaEnv) {
      const vKey = metaEnv.VITE_GEMINI_API_KEY || metaEnv.VITE_API_KEY;
      if (vKey && vKey !== 'PLACEHOLDER_API_KEY') return vKey;
    }
  } catch (e) {}

  try {
    if (typeof process !== 'undefined' && process.env) {
      const pKey = process.env.GEMINI_API_KEY || process.env.API_KEY || process.env.VITE_GEMINI_API_KEY;
      if (pKey && pKey !== 'PLACEHOLDER_API_KEY') return pKey;
    }
  } catch (e) {}

  return "";
}

function getAIClient() {
  const apiKey = getResolvedApiKey();
  if (!apiKey) {
    throw new Error(
      "Chave da API Gemini não configurada. Caso esteja executando no Netlify, configure a variável de ambiente VITE_GEMINI_API_KEY ou GEMINI_API_KEY nas configurações do site (Site configuration > Environment variables)."
    );
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        'User-Agent': 'aistudio-build',
      },
    },
  });
}

function parseGeminiError(error: any): string {
  if (!error) return "Ocorreu um erro desconhecido ao consultar a IA.";
  const rawMsg = error?.message || (typeof error === 'string' ? error : JSON.stringify(error));
  
  if (rawMsg.includes("403") || rawMsg.includes("PERMISSION_DENIED")) {
    return "Erro de permissão (403): Verifique se o projeto possui acesso à API do Gemini ou se a chave GEMINI_API_KEY está configurada corretamente.";
  }
  if (rawMsg.includes("429") || rawMsg.includes("RESOURCE_EXHAUSTED") || rawMsg.includes("quota")) {
    return "Limite de requisições temporário atingido (429). Por favor, aguarde alguns instantes e tente novamente.";
  }
  if (rawMsg.includes("503") || rawMsg.includes("UNAVAILABLE") || rawMsg.includes("high demand")) {
    return "Os servidores do Gemini estão com alta demanda no momento (503). Por favor, aguarde alguns segundos e tente novamente.";
  }
  if (rawMsg.includes("API key not valid") || rawMsg.includes("API_KEY_INVALID")) {
    return "Chave de API inválida. Por favor, verifique a variável GEMINI_API_KEY.";
  }
  return `Erro na consulta à IA: ${rawMsg.slice(0, 180)}`;
}

async function executeWithRetry<T>(
  fn: (model: string) => Promise<T>,
  retriesPerModel = 1
): Promise<T> {
  const allModels = [PRIMARY_MODEL, ...FALLBACK_MODELS];
  let lastError: any = null;

  for (const model of allModels) {
    for (let attempt = 0; attempt <= retriesPerModel; attempt++) {
      try {
        return await fn(model);
      } catch (err: any) {
        lastError = err;
        const msg = err?.message || String(err);
        
        // Fail-fast on non-transient auth/permission errors
        if (msg.includes("403") || msg.includes("PERMISSION_DENIED") || msg.includes("API key not valid")) {
          throw new Error(parseGeminiError(err));
        }

        const isTransient =
          msg.includes("503") ||
          msg.includes("UNAVAILABLE") ||
          msg.includes("high demand") ||
          msg.includes("429") ||
          msg.includes("RESOURCE_EXHAUSTED");

        if (isTransient) {
          if (attempt < retriesPerModel) {
            // Exponential backoff
            await new Promise((resolve) => setTimeout(resolve, 1000 * (attempt + 1)));
            continue;
          }
          // Proceed to next fallback model
          break;
        }

        // If another error, proceed to next model
        break;
      }
    }
  }

  throw new Error(parseGeminiError(lastError));
}

/**
 * Sanitizes and repairs JSON generated by LLMs.
 * Handles truncation, open strings, unbalanced braces/brackets, and repeated whitespace loops.
 */
function repairAndParseJson(rawText: string): { leads: any[] } {
  if (!rawText || !rawText.trim()) {
    return { leads: [] };
  }

  let clean = rawText.replace(/```json\n?/gi, '').replace(/```\n?/gi, '').trim();
  // Collapse excessive runs of spaces or tabs (e.g. infinite space generation bug)
  clean = clean.replace(/[ \t]{4,}/g, ' ');

  // Attempt direct JSON parse first
  try {
    const direct = JSON.parse(clean);
    if (direct && Array.isArray(direct.leads)) {
      return direct;
    }
  } catch {
    // Continue to repair
  }

  // Helper to balance quotes, braces, and brackets
  function autoClose(str: string): string {
    let inString = false;
    let escaped = false;
    for (let i = 0; i < str.length; i++) {
      const c = str[i];
      if (c === '\\' && inString) {
        escaped = !escaped;
      } else if (c === '"' && !escaped) {
        inString = !inString;
      } else {
        escaped = false;
      }
    }

    let s = str.trim();
    if (inString) {
      s += '"';
    }
    s = s.replace(/,\s*$/, '');
    if (s.match(/:\s*$/)) {
      s += '""';
    }

    const stack: string[] = [];
    inString = false;
    escaped = false;
    for (let i = 0; i < s.length; i++) {
      const c = s[i];
      if (c === '\\' && inString) escaped = !escaped;
      else if (c === '"' && !escaped) inString = !inString;
      else if (!inString) {
        if (c === '[' || c === '{') stack.push(c);
        else if (c === ']' && stack[stack.length - 1] === '[') stack.pop();
        else if (c === '}' && stack[stack.length - 1] === '{') stack.pop();
      } else escaped = false;
    }

    while (stack.length > 0) {
      const top = stack.pop();
      if (top === '[') s += ']';
      else if (top === '{') s += '}';
    }
    return s;
  }

  // Attempt 1: Auto-close the entire cleaned text
  try {
    const candidate1 = autoClose(clean);
    const parsed = JSON.parse(candidate1);
    if (parsed && Array.isArray(parsed.leads)) {
      return parsed;
    }
  } catch {
    // Continue to attempt 2
  }

  // Attempt 2: Slice back to the last complete "}" in the leads array
  const lastCompleteObjIndex = clean.lastIndexOf('}');
  if (lastCompleteObjIndex !== -1) {
    const truncated = clean.substring(0, lastCompleteObjIndex + 1);
    try {
      const candidate2 = autoClose(truncated);
      const parsed = JSON.parse(candidate2);
      if (parsed && Array.isArray(parsed.leads)) {
        return parsed;
      }
    } catch {
      // Return empty leads fallback
    }
  }

  return { leads: [] };
}

const SYSTEM_INSTRUCTION = `Você é um assistente sênior de inteligência comercial e prospecção de vendas B2B e B2C de alta precisão.
Diretrizes essenciais de resposta:
1. Retorne SEMPRE um objeto JSON estritamente formatado com a chave "leads".
2. NUNCA gere sequências repetidas de espaços em branco, quebras excessivas ou preenchimento de caracteres.
3. Se qualquer dado de contato (email, telefone, whatsapp, links) não existir ou for incerto, preencha estritamente com string vazia "". NUNCA insira múltiplos espaços para representar campos vazios.
4. Mantenha as descrições e observações concisas, profissionais e objetivas.`;

export async function prospectLeads(params: SearchParams, myCompany?: MyCompany): Promise<{ leads: Lead[], sources: any[] }> {
  let companyContext = '';
  if (myCompany && myCompany.name && myCompany.industry) {
    companyContext = `Sua empresa é ${myCompany.name} da indústria de ${myCompany.industry}.`;
    if (myCompany.website) companyContext += ` O website é ${myCompany.website}.`;
    if (myCompany.description) companyContext += ` Sua descrição é: ${myCompany.description}.`;
    companyContext += ' ';
  }

  let servicesContext = '';
  if (params.servicesOffered) {
    servicesContext = `Sua empresa oferece os seguintes serviços: ${params.servicesOffered}. Encontre leads que possam ter interesse ativo ou necessidade por estes serviços.`;
  }

  const isProfessional = params.targetType === 'professionals';
  const isFreelance = params.targetType === 'freelance_opportunities';
  
  let targetEntity = 'empresas reais';
  let targetRole = 'especialista em prospecção de vendas B2B';
  let nameLabel = 'Nome completo da empresa';
  let industryLabel = 'Setor/Indústria';
  let websiteLabel = 'URL do Website';

  if (isProfessional) {
    targetEntity = 'profissionais (pessoas físicas, autônomos ou especialistas)';
    targetRole = 'especialista em recrutamento e prospecção de profissionais';
    nameLabel = 'Nome completo do profissional';
    industryLabel = 'Profissão / Especialidade';
    websiteLabel = 'URL do Portfólio, LinkedIn ou Site';
  } else if (isFreelance) {
    targetEntity = 'PESSOAS FÍSICAS, influenciadores, criadores de conteúdo ou pequenos empreendedores que estão buscando serviços (NÃO foque em grandes empresas, foque em indivíduos postando em redes sociais ou sites de freelancers)';
    targetRole = 'especialista em encontrar indivíduos e criadores que precisam de ajuda imediata com serviços';
    nameLabel = 'Nome do Contratante / Criador';
    industryLabel = 'Serviço Solicitado';
    websiteLabel = 'Link do Post ou Perfil';
  }

  const prompt = `
    Atue como um ${targetRole}. 
    ${companyContext}Encontre entre 10 e 20 ${targetEntity} reais e qualificados que se encaixam neste critério:
    Nicho/Serviço: ${params.niche}
    Localização: ${params.location}
    ${servicesContext}
    ${isFreelance ? 'FOCO: Encontre postagens de PESSOAS REAIS (criadores, influencers, autônomos) em redes sociais ou fóruns que precisam de ' + params.niche + '. EVITE empresas corporativas, foque no contato direto com o indivíduo.' : 'Objetivo: Identificar leads qualificados para expansão de negócios ou parcerias.'}
    Seja conciso nas descrições e garanta um JSON válido.

    Para cada lead, forneça:
    - ${nameLabel} (campo "name")
    - ${industryLabel} (campo "industry")
    - ${websiteLabel} (campo "website")
    - Uma breve descrição (máximo 1 frase)
    - Pontuação de potencial (0-100)
    - Sugestões de como abordá-los (1 frase curta)
    - Localização exata.
    - E-mail (se disponível, caso contrário use "").
    - Telefone comercial (se disponível, caso contrário use "").
    - Links para redes sociais se disponíveis (caso contrário use "").
    - Número de WhatsApp (campo "whatsapp"): Número com código do país (ex: +5511999998888, +351910760101). Se não houver certeza absoluta, use estritamente string vazia "". NUNCA preencha com múltiplos espaços.
    - Análise de Redes Sociais (campo "socialMediaAnalysis"): Avalie a qualidade da presença digital ('excelente', 'bom', 'regular', 'ruim' ou 'inexistente') e observações curtas.
  `;

  const leadSchema = {
    type: Type.OBJECT,
    properties: {
      leads: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING },
            industry: { type: Type.STRING },
            website: { type: Type.STRING },
            description: { type: Type.STRING },
            potentialScore: { type: Type.NUMBER },
            contactSuggestions: { 
              type: Type.ARRAY, 
              items: { type: Type.STRING } 
            },
            location: { type: Type.STRING },
            email: { type: Type.STRING },
            phone: { type: Type.STRING },
            whatsapp: { type: Type.STRING },
            socialMediaAnalysis: {
              type: Type.OBJECT,
              properties: {
                quality: { 
                  type: Type.STRING,
                  description: "Qualidade da presença no Instagram/Redes Sociais: 'excelente', 'bom', 'regular', 'ruim' ou 'inexistente'"
                },
                observations: { type: Type.STRING, description: "Breve observação sobre o que falta ou o que está ruim." }
              },
              required: ["quality", "observations"]
            },
            socialMedia: {
              type: Type.OBJECT,
              properties: {
                linkedin: { type: Type.STRING },
                instagram: { type: Type.STRING },
                facebook: { type: Type.STRING },
                twitter: { type: Type.STRING }
              }
            }
          },
          required: ["name", "industry", "website", "description", "potentialScore", "contactSuggestions", "location"]
        }
      }
    },
    required: ["leads"]
  };

  try {
    const ai = getAIClient();
    
    // Attempt generation with search grounding first; if search grounding quota is exceeded, fallback to direct generation
    const response = await executeWithRetry(async (modelName) => {
      try {
        return await ai.models.generateContent({
          model: modelName,
          contents: prompt,
          config: {
            systemInstruction: SYSTEM_INSTRUCTION,
            tools: [{ googleSearch: {} }],
            responseMimeType: "application/json",
            temperature: 0.2,
            responseSchema: leadSchema,
          },
        });
      } catch (searchErr: any) {
        const errMsg = searchErr?.message || String(searchErr);
        // If google search grounding tool fails with quota or unsupported error, retry without googleSearch tool
        if (errMsg.includes("quota") || errMsg.includes("429") || errMsg.includes("RESOURCE_EXHAUSTED") || errMsg.includes("tool")) {
          return await ai.models.generateContent({
            model: modelName,
            contents: prompt,
            config: {
              systemInstruction: SYSTEM_INSTRUCTION,
              responseMimeType: "application/json",
              temperature: 0.2,
              responseSchema: leadSchema,
            },
          });
        }
        throw searchErr;
      }
    });

    const rawText = response.text || "";
    const result = repairAndParseJson(rawText);
    const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];

    // Sanitize leads: clean trailing spaces, ensure strings, attach IDs
    const leadsWithIds = (result.leads || []).map((l: any, index: number) => ({
      id: `lead-${Date.now()}-${index}`,
      name: (l.name || "").trim(),
      industry: (l.industry || "").trim(),
      website: (l.website || "").trim(),
      description: (l.description || "").trim(),
      potentialScore: typeof l.potentialScore === 'number' ? l.potentialScore : 75,
      contactSuggestions: Array.isArray(l.contactSuggestions) 
        ? l.contactSuggestions.map((s: any) => String(s).trim()).filter(Boolean)
        : [],
      location: (l.location || "").trim(),
      email: (l.email || "").trim(),
      phone: (l.phone || "").trim(),
      whatsapp: (l.whatsapp || "").trim(),
      socialMediaAnalysis: l.socialMediaAnalysis ? {
        quality: l.socialMediaAnalysis.quality || 'regular',
        observations: (l.socialMediaAnalysis.observations || "").trim()
      } : undefined,
      socialMedia: l.socialMedia ? {
        linkedin: (l.socialMedia.linkedin || "").trim(),
        instagram: (l.socialMedia.instagram || "").trim(),
        facebook: (l.socialMedia.facebook || "").trim(),
        twitter: (l.socialMedia.twitter || "").trim()
      } : undefined
    }));

    return { leads: leadsWithIds, sources };
  } catch (error: any) {
    console.error("Erro na prospecção via Gemini:", error);
    throw error;
  }
}

export async function analyzeLeadOutreach(lead: Lead, myCompany?: MyCompany, targetType?: string): Promise<string> {
  let companyContext = '';
  if (myCompany && myCompany.name && myCompany.industry) {
    companyContext = `Sua empresa, ${myCompany.name}, é da indústria de ${myCompany.industry}.`;
    if (myCompany.description) companyContext += ` Ela é descrita como: ${myCompany.description}.`;
    companyContext += ' ';
  }

  const isProfessional = targetType === 'professionals';
  const isFreelance = targetType === 'freelance_opportunities';

  const targetNameLabel = isFreelance ? 'Contratante' : (isProfessional ? 'Profissional' : 'Empresa');
  const targetIndustryLabel = isFreelance ? 'Serviço Necessário' : (isProfessional ? 'Especialidade' : 'Indústria');

  const prompt = `Crie uma estratégia de abordagem (outreach) personalizada para o seguinte lead:
    ${targetNameLabel}: ${lead.name}
    ${targetIndustryLabel}: ${lead.industry}
    Descrição: ${lead.description}
    Site/Vaga: ${lead.website}
    ${lead.email ? `E-mail: ${lead.email}` : ''}
    ${lead.phone ? `Telefone: ${lead.phone}` : ''}
    
    ${companyContext}A estratégia deve incluir um script de abordagem curto (pode ser para e-mail, LinkedIn ou WhatsApp), focando em como você pode resolver o problema específico do lead. ${isFreelance ? 'Como é uma vaga/projeto, foque em destacar suas habilidades relevantes.' : 'A abordagem deve ser relevante para a sua empresa.'}`;

  try {
    const ai = getAIClient();
    const response = await executeWithRetry(async (modelName) => {
      return await ai.models.generateContent({
        model: modelName,
        contents: prompt,
        config: {
          systemInstruction: "Você é um especialista em vendas e redação de abordagens comerciais de alta conversão.",
          temperature: 0.4,
        }
      });
    });
    return response.text || "Não foi possível gerar a estratégia.";
  } catch (error: any) {
    console.error("Erro na análise de outreach:", error);
    return error.message || "Erro ao gerar estratégia personalizada.";
  }
}
